### ISSUE TITLE
Image get fails for secure Vimeo url

### ISSUE THREAD

**Issue by deegz** [tgezginis/video_thumb#1]
As an example, http://vimeo.com/151746651 works, https://vimeo.com/151746651 does not. The regex needs a little nudge!

I have forked and will create a pull request with a fix...

e.g. line 48 of video_thumb.rb change

`regex = /^http:\/\/(?:.*?)\.?(vimeo)\.com\/(\d+).*$/`
to
`regex = /^https?:\/\/(?:.*?)\.?(vimeo)\.com\/(\d+).*`$/

Not a regex ninja, so don't know if we want to group...

**Comment by tgezginis** [comment]
Hi @deegz,
I merged your PR.  #(0245f886a9ef039890b8d7511a21bef881fd2aa1) 
Thanks for your contribution.
