### ISSUE TITLE
Thumbnails not found for Vimeo alias links

### ISSUE THREAD

**Issue by ianbayne** [tgezginis/video_thumb#5]
For example, a link like `https://vimeo.com/madeinyuhara/watasinoinaihoshi` resolves to `https://vimeo.com/268955649` on Vimeo which should have a thumbnail like `http://i.vimeocdn.com/video/699818221_200x150.jpg`. VideoThumb, however, is not able to grab a thumbnail from the original link.

**Comment by tgezginis** [comment]
@ianbayne Thanks for the feedback. I'll publish new version soon.
